name: Production Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build for Production
        run: npm run build

      - name: Deploy to Production
        run: |
          curl -X POST ${{ secrets.PROD_DEPLOY_HOOK }}
